## Numpy

* Numpy-----Numerical Python
* numpy is a library in python which is used to build different dimensional array

In [4]:
import numpy as np
a=[1,2,3,4,5]
data=np.array(a)
print(data)

[1 2 3 4 5]


In [3]:
type(data)

numpy.ndarray

In [21]:
data1=np.array([[1,2,3,4],[3,4,5,6]])


In [23]:
print(data1)


[[1 2 3 4]
 [3 4 5 6]]


In [12]:
data2=np.array([[1,2,3,4],[3,4,5,6],[1,2,3,4]])

In [25]:
data2

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [1, 2, 3, 4]])

In [14]:
data2.shape

(3, 4)

In [16]:
data=np.arange(0,101)
print(data)



[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [17]:
data.shape


(101,)

In [27]:
data=np.arange(0,100)
data
data2=data.reshape(10,10)
print(data2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [28]:
data2=np.linspace(0,8,10)



In [29]:
data2

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

In [40]:
data=np.random.randint(0,20,size=(2,4))
data


array([[16,  3, 16,  3],
       [16, 14, 19,  0]])

In [47]:
data=np.ones((4,3))

In [48]:
data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
data=np.ones((4,3),int)

In [52]:
data

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [55]:
data=np.zeros((4,3),int)

In [56]:
data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [58]:
n=np.ones((4,3),int)
n
np.vstack([n,n*10])

array([[ 1,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [59]:
n=np.ones((4,3),int)
n
np.hstack([n,n*2])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

 ## Operators

In [61]:
n2=np.array([2,3,4,5])
n1=np.array([1,2,3,4])
n1,n2
n1+n2

array([3, 5, 7, 9])

In [62]:
n2=np.array([2,3,4,5])
n1=np.array([1,2,3,4])
n1,n2
n1-n2

array([-1, -1, -1, -1])

In [63]:
n1*n2

array([ 2,  6, 12, 20])

In [64]:
n1/n2

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [65]:
n1**n2

array([   1,    8,   81, 1024], dtype=int32)

In [66]:
n1%n2

array([1, 2, 3, 4], dtype=int32)

In [67]:
n1**3

array([ 1,  8, 27, 64], dtype=int32)

In [68]:
n1.all()

True

In [69]:
n1&n2

array([0, 2, 0, 4], dtype=int32)

In [70]:
n1.dot(n2)

40

In [72]:
data1

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [73]:
data1.T

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])

In [74]:
print(data1.transpose())

[[1 3]
 [2 4]
 [3 5]
 [4 6]]


In [75]:
data1

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [78]:
data1.max()

6

In [79]:
data1.min()

1

In [81]:
data1.sum()

28

In [82]:
data1.mean()

3.5

In [83]:
data1[::-1]

array([[3, 4, 5, 6],
       [1, 2, 3, 4]])

In [84]:
np.sqrt(data1)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.73205081, 2.        , 2.23606798, 2.44948974]])

## an emirp(prime spelled backwords)is non plaindromic prime which when its digit are reversed,makes another prime.eg 13 is a prime and so is 31.both are thererfore emirps


In [3]:
def isprime(n):
    if n==0 or n==1:
        return False
    flag=True
    for i in range(2,int(n**(1/2))+1):
        if n%i==0:
            flag=False
    return flag

tc=int(input())
for t in range(tc):
    n=input('enter a number : ')
    m='0'
    if '6' in n:
        m=n.replace('6','s')
    if '9' in m:
        m=m.replace('9','6')
    if 's' in m:
        
        m=m.replace('s','9')

    if isprime(int(n)) and isprime(int(n[::-1])) and isprime(int(m)) and isprime(int(m[::-1])):
        print('beminp')
    elif isprime(int(n)) and isprime(int(n[::-1])):
        print("eminp")
    else:
        print('no')
        


2
enter a number : 13
eminp
enter a number : 31
eminp
